version: '3.8'

services:
  unit_test:
    build: 
      dockerfile: Dockerfile
      context: .
    command: npm run test
    ports:
      - '5000:5000'
    networks:
      - test-network
    depends_on:
      - postgres_test
    environment:
      TEST_DB_HOST: postgres_test
      TEST_DB_PORT: 5432
      TEST_DB_USERNAME: user
      TEST_DB_PASSWORD: password
      TEST_DB_NAME: tundrax_test_db
      JWT_SERVER_SECRET: sUp4hS3cr37kE9c0D3
      TOKEN_LIFETIME_IN_SECONDS : 1h
    volumes:
      - .:/usr/src/app
      - /usr/src/app/e2e
      - /usr/src/app/node_modules

  e2e_test:
    build: 
      dockerfile: Dockerfile
      context: .
    command: npm run test:e2e
    ports:
      - '5000:5000'
    networks:
      - test-network
    depends_on:
      - postgres_test
    environment:
      TEST_DB_HOST: postgres_test
      TEST_DB_PORT: 5432
      TEST_DB_USERNAME: user
      TEST_DB_PASSWORD: password
      TEST_DB_NAME: tundrax_test_db
      JWT_SERVER_SECRET: sUp4hS3cr37kE9c0D3
      TOKEN_LIFETIME_IN_SECONDS : 1h
    volumes:
      - .:/usr/src/app
      - /usr/src/app/e2e
      - /usr/src/app/node_modules

  postgres_test:
    image: postgres
    ports:
      - '5432:5432'
    networks:
      - test-network
    environment:
      POSTGRES_DB: tundrax_test_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

networks:
  app-network:
    driver: bridge
  test-network:
    driver: bridge
