version: '3.8'

services:
  nestjs_app:
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - '5000:5000'
    networks:
      - app-network
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_NAME: tundrax_db
      JWT_SERVER_SECRET: sUp4hS3cr37kE9c0D3
      TOKEN_LIFETIME_IN_SECONDS : 1h
    volumes:
      - .:/usr/src/app
      - /usr/src/app/e2e
      - /usr/src/app/node_modules

  postgres:
    image: postgres
    ports:
      - '5438:5432'
    networks:
      - app-network
    environment:
      POSTGRES_DB: tundrax_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

networks:
  app-network:
    driver: bridge
